# Generated by Django 4.1.1 on 2022-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('cats', models.BooleanField(blank=True, default=False, null=True)),
                ('dogs', models.BooleanField(blank=True, default=False, null=True)),
                ('pet_policy_text', models.TextField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('min_beds', models.IntegerField(blank=True, null=True)),
                ('max_beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('min_baths', models.IntegerField(blank=True, null=True)),
                ('max_baths', models.IntegerField(blank=True, null=True)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pictures', models.URLField()),
                ('pictures1', models.URLField()),
            ],
        ),
    ]
