# Generated by Django 4.1.1 on 2022-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_baths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_beds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='min_baths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='min_beds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
