# Generated by Django 4.1.1 on 2022-09-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_apartment_county_alter_apartment_max_baths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='sqft',
        ),
    ]
