# Generated by Django 4.1.1 on 2022-09-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0004_alter_apartment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
