# Generated by Django 4.1.1 on 2022-09-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestateapp', '0005_delete_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('cats', models.BooleanField(blank=True, default=False, null=True)),
                ('dogs', models.BooleanField(blank=True, default=False, null=True)),
                ('pet_policy_text', models.TextField(blank=True, null=True)),
                ('min_beds', models.FloatField(blank=True, null=True)),
                ('max_beds', models.FloatField(blank=True, null=True)),
                ('min_baths', models.FloatField(blank=True, null=True)),
                ('max_baths', models.FloatField(blank=True, null=True)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pictures', models.URLField()),
                ('pictures1', models.URLField()),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
